### ISSUE TITLE
Unable to install app

### ISSUE THREAD

**Issue by galimpian** [figma-plus/installer#12]
```
Error: ENOENT: no such file or directory, open '/Users/name/Library/Application Support/Figma Plus/input/window_manager.js'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at injectSync (/Applications/Figma Plus.app/Contents/Resources/app.asar/node_modules/inject-code/lib/index.js:163:19)
    at module.exports (/Applications/Figma Plus.app/Contents/Resources/app.asar/node_modules/inject-code/lib/index.js:227:22)
    at startInjecting (/Applications/Figma Plus.app/Contents/Resources/app.asar/renderer.js:266:3)
    at checkFigmaBeforeRunning (/Applications/Figma Plus.app/Contents/Resources/app.asar/renderer.js:181:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

---

Figma Plus 1.0.0
Electron 3.0.9
darwin 18.5.0
Locale: en-US

**Comment by galimpian** [comment]
resolved, need to have the desktop app first.
