### ISSUE TITLE
Error after clicking Install app. Mac

### ISSUE THREAD

**Issue by Alkhova** [figma-plus/installer#14]
```
Error: EACCES: permission denied, copyfile '/Applications/Figma.app/Contents/Resources/app.asar' -> '/Applications/Figma.app/Contents/Resources/app.asar.bk'
    at Object.fs.copyFileSync (original-fs.js:2026:3)
    at writePacked (/private/var/folders/7b/rh7gjfh55_x95cs1284r26qcxg20xy/T/AppTranslocation/1851CFF7-E2B3-4AC0-A298-167658474332/d/Figma Plus.app/Contents/Resources/app.asar/renderer.js:281:18)
    at /private/var/folders/7b/rh7gjfh55_x95cs1284r26qcxg20xy/T/AppTranslocation/1851CFF7-E2B3-4AC0-A298-167658474332/d/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/asar.js:157:18
    at writeFileListToStream (/private/var/folders/7b/rh7gjfh55_x95cs1284r26qcxg20xy/T/AppTranslocation/1851CFF7-E2B3-4AC0-A298-167658474332/d/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:42:10)
    at ReadStream.<anonymous> (/private/var/folders/7b/rh7gjfh55_x95cs1284r26qcxg20xy/T/AppTranslocation/1851CFF7-E2B3-4AC0-A298-167658474332/d/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:37:16)
    at ReadStream.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

---

Figma Plus 1.0.0
Electron 3.0.9
darwin 17.7.0
Locale: en-GB

**Comment by sweeting** [comment]
I get this as well.

```
Error: EACCES: permission denied, copyfile '/Applications/Figma.app/Contents/Resources/app.asar' -> '/Applications/Figma.app/Contents/Resources/app.asar.bk'
    at Object.fs.copyFileSync (original-fs.js:2026:3)
    at writePacked (/Applications/Figma Plus.app/Contents/Resources/app.asar/renderer.js:281:18)
    at /Applications/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/asar.js:157:18
    at writeFileListToStream (/Applications/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:42:10)
    at ReadStream.<anonymous> (/Applications/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:37:16)
    at ReadStream.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

---

Figma Plus 1.0.0
Electron 3.0.9
darwin 18.5.0
Locale: en-US

**Comment by jackiecorn** [comment]
We are still investigating into this issue.
Meanwhile, can you help us to test if this works:

1. Copy and paste you Figma app from the Applications folder onto your Desktop (make sure it's not a 2. shortcut but an actual copy of the app file)
3. Delete the Figma app from Applications folder.
4. Run the Figma Plus installer.
5. If it asks to locate your app, point it to your Figma app on the desktop.
6. Open the Figma app.

Please let us know how this goes, it will help us to identify the problem.

**Comment by gabrielvaz** [comment]
Same here. Just tried to do what @jackiecorn did and didn`t worked.


```
Unhandled Error
Error: EACCES: permission denied, copyfile '/Users/gabrielvaz/Desktop/Figma.app/Contents/Resources/app.asar' -> '/Users/gabrielvaz/Desktop/Figma.app/Contents/Resources/app.asar.bk'
    at Object.fs.copyFileSync (original-fs.js:2026:3)
    at writePacked (/Users/gabrielvaz/Desktop/Figma Plus.app/Contents/Resources/app.asar/renderer.js:281:18)
    at /Users/gabrielvaz/Desktop/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/asar.js:157:18
    at writeFileListToStream (/Users/gabrielvaz/Desktop/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:42:10)
    at ReadStream.<anonymous> (/Users/gabrielvaz/Desktop/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:37:16)
```

**Comment by Alkhova** [comment]
Tried to replace Figma at Desktop. It's doesn't work

Unhandled Error
Error: EACCES: permission denied, copyfile '/Users/alhova.d/Desktop/Figma.app/Contents/Resources/app.asar' -> '/Users/alhova.d/Desktop/Figma.app/Contents/Resources/app.asar.bk'
    at Object.fs.copyFileSync (original-fs.js:2026:3)
    at writePacked (/private/var/folders/7b/rh7gjfh55_x95cs1284r26qcxg20xy/T/AppTranslocation/C7ADE20A-5619-44CC-9FCF-7EB9851306D9/d/Figma Plus.app/Contents/Resources/app.asar/renderer.js:281:18)
    at /private/var/folders/7b/rh7gjfh55_x95cs1284r26qcxg20xy/T/AppTranslocation/C7ADE20A-5619-44CC-9FCF-7EB9851306D9/d/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/asar.js:157:18
    at writeFileListToStream (/private/var/folders/7b/rh7gjfh55_x95cs1284r26qcxg20xy/T/AppTranslocation/C7ADE20A-5619-44CC-9FCF-7EB9851306D9/d/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:42:10)
    at ReadStream.<anonymous> (/private/var/folders/7b/rh7gjfh55_x95cs1284r26qcxg20xy/T/AppTranslocation/C7ADE20A-5619-44CC-9FCF-7EB9851306D9/d/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:37:16)
